from django.db import models
from django.db.models.enums import Choices
from django.core.exceptions import ValidationError


# Create your models here.

DOCUMENTOS = [
        ('RC', 'Registro Civil'),
        ('TI', 'Tarjeta de identidad'),
        ('CC', 'Cédula de Ciudadanía'),
        ('CE', 'Cédula de Extranjería'),
        ('PA', 'Pasaporte'),
        ('MS', 'Menor sin identidad'),
        ('AS', 'Adulto sin identidad'),
        ]

GENERO = [
    ('F', 'Femenino'),
    ('M', 'Masculino')
    ]

COMUNAS = [
    ('1 - Popular', 'Comuna 1 - Popular'),
    ('2 - Santa Cruz', 'Comuna 2 - Santa Cruz'),
    ('3 - Manrique', 'Comuna 3 - Manrique'),
    ('4 - Aranjuez', 'Comuna 4 - Aranjuez'),
    ('5 - Castilla', 'Comuna 5 - Castilla'),
    ('6 - Doce de Octubre', 'Comuna 6 - Doce de Octubre'),
    ('7 - Robledo', 'Comuna 7 - Robledo'),
    ('8 - Villa Hermosa', 'Comuna 8 - Villa Hermosa'),
    ('9 - Buenos Aires', 'Comuna 9 - Buenos Aires'),
    ('10 - La Candelaria', 'Comuna 10 - La Candelaria'),
    ('11 - Laureles-Estadio', 'Comuna 11 - Laureles-Estadio'),
    ('12 - La América', 'Comuna 12 - La América'),
    ('13 - San Javier', 'Comuna 13 - San Javier'),
    ('14 - El Poblado', 'Comuna 14 - El Poblado'),
    ('15 - Guayabal', 'Comuna 15 - Guayabal'),
    ('16 - Belén', 'Comuna 16 - Belén'),
    ]

BARRIOS = {
    COMUNAS[0]: [('H', 'Hola'),('M', 'Mundo')]
}

VACUNAS = [
        ('Pfizer', 'Pfizer/BioNtech'),
        ('AstraZeneca', 'AstraZeneca/Oxford'),
        ('Jansen', 'Jansen/Johnson & Johnson'),
        ]

PUESTOS = [
    ('ADILAB PROGRAMAS ESPECIALES', 'ADILAB PROGRAMAS ESPECIALES'),
    ('ASCODES S.A.S.', 'ASCODES S.A.S.'),
    ('ASCODESV', 'ASCODESV'),
    ('ASEMECO S.A.S', 'ASEMECO S.A.S'),
    ('ASESORIAS Y SOLUCIONES INTEGRALES EN SALUD A&S S.A.', 'ASESORIAS Y SOLUCIONES INTEGRALES EN SALUD A&S S.A.'),
    ('ASISTENCIA CIENTIFICA DE ALTA COMPLEJIDAD SAS', 'ASISTENCIA CIENTIFICA DE ALTA COMPLEJIDAD SAS'),
    ('ASOCIACION PROBIENESTAR DE LA FAMILIA COLOMBIANA PROFAMILIA', 'ASOCIACION PROBIENESTAR DE LA FAMILIA COLOMBIANA PROFAMILIA'),
    ('CENTOR DE SALUD PABLO VI - EMPRESA SOCIAL DEL ESTADO METROSA', 'CENTOR DE SALUD PABLO VI - EMPRESA SOCIAL DEL ESTADO METROSA'),
    ('CENTRO DE SALUD ALFONSO LÓPEZ', 'CENTRO DE SALUD ALFONSO LÓPEZ'),
    ('CENTRO DE SALUD ALTAVISTA', 'CENTRO DE SALUD ALTAVISTA'),
    ('CENTRO DE SALUD ARANJUEZ', 'CENTRO DE SALUD ARANJUEZ'),
    ('CENTRO DE SALUD BELEN RINCON', 'CENTRO DE SALUD BELEN RINCON'),
    ('CENTRO DE SALUD CAMPO VALDES', 'CENTRO DE SALUD CAMPO VALDES'),
    ('CENTRO DE SALUD CARPINELO', 'CENTRO DE SALUD CARPINELO'),
    ('CENTRO DE SALUD CIVITON', 'CENTRO DE SALUD CIVITON'),
    ('CENTRO DE SALUD DEL POBLADO', 'CENTRO DE SALUD DEL POBLADO'),
    ('CENTRO DE SALUD EL LIMONAR', 'CENTRO DE SALUD EL LIMONAR'),
    ('CENTRO DE SALUD EL RAIZAL', 'CENTRO DE SALUD EL RAIZAL'),
    ('CENTRO DE SALUD EL TRIUNFO', 'CENTRO DE SALUD EL TRIUNFO'),
    ('CENTRO DE SALUD ENCISO', 'CENTRO DE SALUD ENCISO'),
    ('CENTRO DE SALUD ESTADIO', 'CENTRO DE SALUD ESTADIO'),
    ('CENTRO DE SALUD GUAYABAL', 'CENTRO DE SALUD GUAYABAL'),
    ('CENTRO DE SALUD LA CRUZ', 'CENTRO DE SALUD LA CRUZ'),
    ('CENTRO DE SALUD LA ESPERANZA', 'CENTRO DE SALUD LA ESPERANZA'),
    ('CENTRO DE SALUD LA LOMA', 'CENTRO DE SALUD LA LOMA'),
    ('CENTRO DE SALUD LLANADITAS', 'CENTRO DE SALUD LLANADITAS'),
    ('CENTRO DE SALUD LORETO', 'CENTRO DE SALUD LORETO'),
    ('CENTRO DE SALUD LUIS JAVIER GARCIA', 'CENTRO DE SALUD LUIS JAVIER GARCIA'),
    ('CENTRO DE SALUD MANANTIAL DE VIDA', 'CENTRO DE SALUD MANANTIAL DE VIDA'),
    ('CENTRO DE SALUD MARGARITAS', 'CENTRO DE SALUD MARGARITAS'),
    ('CENTRO DE SALUD MORAVIA', 'CENTRO DE SALUD MORAVIA'),
    ('CENTRO DE SALUD PALMITAS', 'CENTRO DE SALUD PALMITAS'),
    ('CENTRO DE SALUD PICACHO', 'CENTRO DE SALUD PICACHO'),
    ('CENTRO DE SALUD POPULAR', 'CENTRO DE SALUD POPULAR'),
    ('CENTRO DE SALUD ROBLEDO', 'CENTRO DE SALUD ROBLEDO'),
    ('CENTRO DE SALUD SALVADOR', 'CENTRO DE SALUD SALVADOR'),
    ('CENTRO DE SALUD SAN BLAS', 'CENTRO DE SALUD SAN BLAS'),
    ('CENTRO DE SALUD SAN CAMILO', 'CENTRO DE SALUD SAN CAMILO'),
    ('CENTRO DE SALUD SAN LORENZO', 'CENTRO DE SALUD SAN LORENZO'),
    ('CENTRO DE SALUD SANTA ELENA', 'CENTRO DE SALUD SANTA ELENA'),
    ('CENTRO DE SALUD SANTA ROSA DE LIMA', 'CENTRO DE SALUD SANTA ROSA DE LIMA'),
    ('CENTRO DE SALUD SANTANDER', 'CENTRO DE SALUD SANTANDER'),
    ('CENTRO DE SALUD SANTO DOMINGO', 'CENTRO DE SALUD SANTO DOMINGO'),
    ('CENTRO DE SALUD SOL DE ORIENTE', 'CENTRO DE SALUD SOL DE ORIENTE'),
    ('CENTRO DE SALUD TRINIDAD', 'CENTRO DE SALUD TRINIDAD'),
    ('CENTRO DE SALUD VILLA DEL SOCORRO', 'CENTRO DE SALUD VILLA DEL SOCORRO'),
    ('CENTRO DE SALUD VILLA LAURA', 'CENTRO DE SALUD VILLA LAURA'),
    ('CENTRO DE SALUD VILLATINA', 'CENTRO DE SALUD VILLATINA'),
    ('CENTRO INTEGRAL DE REUMATOLOGÍA REUMALAB SAS', 'CENTRO INTEGRAL DE REUMATOLOGÍA REUMALAB SAS'),
    ('CENTRO INTEGRAL DE SALUD ARANJUEZ', 'CENTRO INTEGRAL DE SALUD ARANJUEZ'),
    ('CENTRO INTEGRAL DE SALUD LA 80', 'CENTRO INTEGRAL DE SALUD LA 80'),
    ('CENTRO INTEGRAL DE SALUD MANRIQUE', 'CENTRO INTEGRAL DE SALUD MANRIQUE'),
    ('CENTRO INTEGRAL DE SALUD SAN IGNACIO', 'CENTRO INTEGRAL DE SALUD SAN IGNACIO'),
    ('CLINICA COLSANITAS S.A.', 'CLINICA COLSANITAS S.A.'),
    ('CLINICA DEL PRADO CIUDAD DEL RIO', 'CLINICA DEL PRADO CIUDAD DEL RIO'),
    ('CLINICA EL ROSARIO SEDE EL TESORO', 'CLINICA EL ROSARIO SEDE EL TESORO'),
    ('CLINICA ESIMED DE LA 80', 'CLINICA ESIMED DE LA 80'),
    ('CLINICA UNIVERSITARIA BOLIVARIANA', 'CLINICA UNIVERSITARIA BOLIVARIANA'),
    ('CLÍNICA LAS AMERICAS', 'CLÍNICA LAS AMERICAS'),
    ('COOMEVA EPS IPS INTEGRADOS', 'COOMEVA EPS IPS INTEGRADOS'),
    ('COOMSOCIAL ESTADIO SEDE 2', 'COOMSOCIAL ESTADIO SEDE 2'),
    ('COOMSOCIAL ESTADIO SEDE 3', 'COOMSOCIAL ESTADIO SEDE 3'),
    ('COOPERATIVA ANTIOQUEÑA DE SALUD SEDE ALTERNA CENTRO', 'COOPERATIVA ANTIOQUEÑA DE SALUD SEDE ALTERNA CENTRO'),
    ('COOPERATIVA ANTIOQUEÑA DE SALUD SEDE NORTE', 'COOPERATIVA ANTIOQUEÑA DE SALUD SEDE NORTE'),
    ('COOPERATIVA DE SALUD SAN ESTEBAN', 'COOPERATIVA DE SALUD SAN ESTEBAN'),
    ('COOPERATIVA DE SALUD SAN ESTEBAN CTA', 'COOPERATIVA DE SALUD SAN ESTEBAN CTA'),
    ('COOPSANA CALASANZ', 'COOPSANA CALASANZ'),
    ('CORPORACION COLOMBIA SALUDABLE', 'CORPORACION COLOMBIA SALUDABLE'),
    ('CORPORACION IPS CEDISALUD', 'CORPORACION IPS CEDISALUD'),
    ('CORPORACIÒN MEDICA S.A LTDA- COLMEDICOS S.A', 'CORPORACIÒN MEDICA S.A LTDA- COLMEDICOS S.A'),
    ('Coopsana Avenida Oriental', 'Coopsana Avenida Oriental'),
    ('Dejando Huella Fertilidad', 'Dejando Huella Fertilidad'),
    ('E.S.E. HOSPITAL LA MARIA', 'E.S.E. HOSPITAL LA MARIA'),
    ('EPS SANITAS CENTRO MEDICO MEDELLIN', 'EPS SANITAS CENTRO MEDICO MEDELLIN'),
    ('EUGENIO ANTONIO RESTREPO', 'EUGENIO ANTONIO RESTREPO'),
    ('FACULTAD DE MEDICINA HOSPITAL SAN VICENTE DE PAUL', 'FACULTAD DE MEDICINA HOSPITAL SAN VICENTE DE PAUL'),
    ('FUNDACION CENTRO DE INVESTIGACION CLINICA CIC', 'FUNDACION CENTRO DE INVESTIGACION CLINICA CIC'),
    ('FUNDACION HOSPITALARIA IPS UNIVERSITARIA ADVENTISTA', 'FUNDACION HOSPITALARIA IPS UNIVERSITARIA ADVENTISTA'),
    ('HOSPITAL GENERAL DE MEDELLÍN LUZ CASTRO DE GUTIERREZ, EMPRESA SOCIAL DEL ESTADO', 'HOSPITAL GENERAL DE MEDELLÍN LUZ CASTRO DE GUTIERREZ, EMPRESA SOCIAL DEL ESTADO'),
    ('HOSPITAL PABLO TOBON URIBE', 'HOSPITAL PABLO TOBON URIBE'),
    ('I P S FUNSALUD LA 33', 'I P S FUNSALUD LA 33'),
    ('INSTITUTO DEL TORAX S.A.S', 'INSTITUTO DEL TORAX S.A.S'),
    ('IPS CENTRO DE VACUNACION INTEGRAL S.A.S', 'IPS CENTRO DE VACUNACION INTEGRAL S.A.S'),
    ('IPS SALUD SURA SAO PAULO MEDELLIN', 'IPS SALUD SURA SAO PAULO MEDELLIN'),
    ('IPS SURA ALMACENTRO MEDELLIN', 'IPS SURA ALMACENTRO MEDELLIN'),
    ('IPS SURA CENTRO MEDELLIN', 'IPS SURA CENTRO MEDELLIN'),
    ('IPS SURA CORDOBA MEDELLIN', 'IPS SURA CORDOBA MEDELLIN'),
    ('IPS SURA INDUSTRIALES MEDELLIN', 'IPS SURA INDUSTRIALES MEDELLIN'),
    ('IPS SURA LOS MOLINOS MEDELLIN', 'IPS SURA LOS MOLINOS MEDELLIN'),
    ('IPS SURA MONTERREY MEDELLIN', 'IPS SURA MONTERREY MEDELLIN'),
    ('IPS SURA SAMAN MEDELLIN', 'IPS SURA SAMAN MEDELLIN'),
    ('IPS SURA SAN DIEGO', 'IPS SURA SAN DIEGO'),
    ('IPS VACUNANDO S.A.S.', 'IPS VACUNANDO S.A.S.'),
    ('J K VACUNAMOS S.A.S', 'J K VACUNAMOS S.A.S'),
    ('Laborum sld S.A.S', 'Laborum sld S.A.S'),
    ('OLGA PATRICIA ROBLEDO NOREÑA', 'OLGA PATRICIA ROBLEDO NOREÑA'),
    ('OMNISALUD # 2', 'OMNISALUD # 2'),
    ('ORGANIZACION INDIGENA DE ANTIOQUIA', 'ORGANIZACION INDIGENA DE ANTIOQUIA'),
    ('PREVILABOR S.A.S', 'PREVILABOR S.A.S'),
    ('PROMEDAN IPS CENTRO', 'PROMEDAN IPS CENTRO'),
    ('PROSALCO IPS SAN JUAN', 'PROSALCO IPS SAN JUAN'),
    ('SALUD VITAL Y RIESGOS PROFESIONALES IPS SAS', 'SALUD VITAL Y RIESGOS PROFESIONALES IPS SAS'),
    ('SEDE ADMINISTRATIVA EDIFICIO SACATIN', 'SEDE ADMINISTRATIVA EDIFICIO SACATIN'),
    ('SEDE BOSTON', 'SEDE BOSTON'),
    ('SEDE CENTRO', 'SEDE CENTRO'),
    ('SEDE PRADO', 'SEDE PRADO'),
    ('SEDE SAN DIEGO', 'SEDE SAN DIEGO'),
    ('SEDE SAN JUAN', 'SEDE SAN JUAN'),
    ('SERVICIOS INMUNOLOGICOS PREVINM', 'SERVICIOS INMUNOLOGICOS PREVINM'),
    ('SERVICIOS MEDICOS SAN IGNACIO AGUACATALA S.A.S', 'SERVICIOS MEDICOS SAN IGNACIO AGUACATALA S.A.S'),
    ('SERVICIOS MEDICOS SAN IGNACIO S.A.S', 'SERVICIOS MEDICOS SAN IGNACIO S.A.S'),
    ('SINERGIA SALUD ATENCION BASICA BELEN', 'SINERGIA SALUD ATENCION BASICA BELEN'),
    ('SINERGIA SALUD ATENCION BASICA POBLADO', 'SINERGIA SALUD ATENCION BASICA POBLADO'),
    ('SINERGIA SALUD ATENCIÓN BASICA JUNIN', 'SINERGIA SALUD ATENCIÓN BASICA JUNIN'),
    ('SINERGIA SALUD ATENCIÓN BÁSICA PRADO', 'SINERGIA SALUD ATENCIÓN BÁSICA PRADO'),
    ('SOCIEDAD MEDICA ANTIOQUEÑA S.A. SOMA', 'SOCIEDAD MEDICA ANTIOQUEÑA S.A. SOMA'),
    ('SUPLIMED HOSPITALARIO', 'SUPLIMED HOSPITALARIO'),
    ('UNIDAD HOSPITALARIA DE BELEN HECTOR ABAD GOMEZ', 'UNIDAD HOSPITALARIA DE BELEN HECTOR ABAD GOMEZ'),
    ('UNIDAD HOSPITALARIA DE CASTILLA JAIME TOBON ARBELAEZ', 'UNIDAD HOSPITALARIA DE CASTILLA JAIME TOBON ARBELAEZ'),
    ('UNIDAD HOSPITALARIA DE MANRRIQUE HERMENEGILDO DE FEX', 'UNIDAD HOSPITALARIA DE MANRRIQUE HERMENEGILDO DE FEX'),
    ('UNIDAD HOSPITALARIA DOCE DE OCTUBRE LUIS CARLOS GALAN SARMIENTO', 'UNIDAD HOSPITALARIA DOCE DE OCTUBRE LUIS CARLOS GALAN SARMIENTO'),
    ('UNIDAD HOSPITALARIA NUEVO OCCIDENTE', 'UNIDAD HOSPITALARIA NUEVO OCCIDENTE'),
    ('UNIDAD HOSPITALARIA SANTA CRUZ', 'UNIDAD HOSPITALARIA SANTA CRUZ'),
    ('UNIDAD INTEGRAL EN SALUD LAURELES', 'UNIDAD INTEGRAL EN SALUD LAURELES'),
    ('UNIDAD INTEGRAL EN SALUD POBLADO', 'UNIDAD INTEGRAL EN SALUD POBLADO'),
    ('UNIDAD PRESTADORA DE SERVICIOS DE SALUD SAN ANTONIO DE PRADO HOSPITAL DIEGO ECHAVARRIA MISAS', 'UNIDAD PRESTADORA DE SERVICIOS DE SALUD SAN ANTONIO DE PRADO HOSPITAL DIEGO ECHAVARRIA MISAS'),
    ('UNIDAD PRESTADORA DE SERVICIOS DE SALUD SAN CRISTOBAL', 'UNIDAD PRESTADORA DE SERVICIOS DE SALUD SAN CRISTOBAL'),
    ('UNIDAD PRESTADORA DE SERVICIOS DE SALUD SAN JAVIER', 'UNIDAD PRESTADORA DE SERVICIOS DE SALUD SAN JAVIER'),
    ('VIVA 1 A IPS MEDELLÍN', 'VIVA 1 A IPS MEDELLÍN'),
    ('VIVA 1A IPS ESTADIO', 'VIVA 1A IPS ESTADIO'),
    ('VIVA 1A IPS PRADO', 'VIVA 1A IPS PRADO'),
    ('VIVA 1A IPS VILLANUEVA', 'VIVA 1A IPS VILLANUEVA'),
    ]

class Vacunado(models.Model):
    # django-crispy-forms
    nombres=models.CharField(max_length=60)
    apellidos=models.CharField(max_length=60)
    tipo_documento=models.CharField('Tipo de documento', max_length=2, choices=DOCUMENTOS)
    numero_documento=models.CharField('Número de documento' ,max_length=10)
    fecha_nacimiento=models.DateField('Fecha de nacimiento', auto_now=False, auto_now_add=False,
                            help_text="Por favor use el siguiente formato: <em>YYYY-MM-DD</em>.")
    genero=models.CharField(max_length=1, choices=GENERO, verbose_name="Género")
    correo_electronico=models.EmailField('Correo electrónico', max_length=120)
    comuna_residencia=models.CharField('Comuna de residencia', max_length=30, choices=COMUNAS)
    # barrio_residencia=models.CharField(max_length=30, choices=BARRIOS.get(comuna_residencia))
    telefono_fijo=models.CharField('Teléfono fijo', max_length=7, null=True, blank=True)
    telefono_movil=models.CharField('Teléfono movil', max_length=10)
    fecha_vacunacion=models.DateTimeField('Fecha de vacunación', auto_now=False, auto_now_add=False,
                            help_text="Por favor use el siguiente formato: <em>YYYY-MM-DD</em>.")
    vacuna_aplicada=models.CharField(max_length=30, choices=VACUNAS)
    # fecha_prox_vacuna
    Lote=models.CharField('Lote de vacuna', max_length=20)
    segunda_vacuna=models.BooleanField('Segunda vacuna aplicada')
    punto_de_vacunacion=models.CharField('Punto de vacunación', max_length=120, choices=PUESTOS)

    def __str__(self):
        return '%s %s' % (self.nombres, self.correo_electronico)